/**
 * `scripts/probe-band-heights.ts` — measure the BAND GEOMETRY of a captured
 * render, rather than reading it.
 *
 * WHY IT EXISTS. `docs/research/omp-stats-tui/RENDER-OUTPUT.txt` carries a table
 * of rows-per-band, and that table was wrong twice: once because a hand-counted
 * measure was off by one band boundary, and once because it described the shape
 * a fix was INTENDED to produce rather than the one it produced. A documented
 * number the artifact beside it contradicts is as much a lie as a chart with no
 * floor — so the numbers in that file are now generated by running this.
 *
 * WHAT IT MEASURES, per band, from the captured text:
 *
 *   rows    — how many rows the band occupies
 *   ink     — filled cells across the whole band
 *   floor   — 1 when the band's LAST row is a full run of `axisLine`
 *   blank   — rows in the band carrying no glyph at all
 *
 * `floor` and `blank` are separate columns on purpose. A row-COUNT check cannot
 * see a missing floor, because the defective bands had the right number of rows;
 * what they lacked was the GLYPH. The defect this module was written to catch
 * was invisible until the ink was counted.
 *
 * A band is the contiguous run of chart rows immediately ABOVE its label:
 * `renderSeriesChart` labels a band after its marks.
 *
 * Usage: bun scripts/probe-band-heights.ts <capture.txt> [label…]
 *   With no labels, every four-series "Cost by billing component" chart in the
 *   file is measured. With labels, only those bands are measured.
 */

import { readFileSync } from "node:fs";

const ANSI = /\x1b\[[0-9;]*m/g;
const AXIS = "_";
const FILL = "█";

const path = process.argv[2];
if (!path) {
	console.error("usage: bun scripts/probe-band-heights.ts <capture.txt> [label…]");
	process.exit(1);
}
const wanted = process.argv.slice(3);
const lines = readFileSync(path, "utf8").replace(ANSI, "").split("\n");

/**
 * The chart body: past the overlay's sidebar gutter and inside the frame.
 *
 * The showcase wraps its body in `│ … │`, so the trailing border has to come off
 * too — a label line still reading `│ Input  │` matches no label set, which is
 * how a whole showcase frame once measured as containing zero bands.
 */
const body = (line: string): string => {
	if (!line.startsWith("│")) return line.replace(/│/g, " ");
	const rest = line.slice(1);
	const divider = rest.indexOf("│");
	return (divider < 0 ? rest : rest.slice(divider + 1)).replace(/│\s*$/, "");
};

const isFloor = (line: string): boolean => new RegExp(`^\\s*${AXIS}{20,}\\s*$`).test(body(line));

// The labels that close a chart band. A band is named by its SERIES, and a
// series label is followed only by whitespace — that is what separates it from a
// card title, a table cell or a stat tile, all of which carry figures to the
// right. Scoping to these keeps stat tiles and tables out of the measurement,
// which is what made an early version of this tool report floors missing on rows
// that are not charts at all.
const BAND_LABELS = new Set([
	"Input", "Output", "Cache read", "Cache write", "Uncached input",
	"Cost", "Succeeded", "Failed",
]);

const isLabel = (line: string): boolean => {
	const text = body(line).trim();
	return BAND_LABELS.has(text);
};

interface Band {
	label: string;
	rows: number;
	ink: number;
	floor: number;
	blank: number;
}
// A band is the run of chart rows immediately ABOVE its label: `renderSeriesChart`
// labels a band after its marks. So walk the file, remember every label row, and
// for each one take the contiguous block of non-blank rows above it.
interface LabelRow {
	index: number;
	name: string;
}

const labels: LabelRow[] = [];
lines.forEach((line, index) => {
	if (isLabel(line)) labels.push({ index, name: body(line).trim() });
});

const bands: Band[] = [];
for (const [position, { index, name }] of labels.entries()) {
	// Walk up from the label while the rows belong to the band: anything from the
	// previous label onward is fair game, and a blank row ends the band.
	const from = position > 0 ? labels[position - 1]!.index + 1 : 0;
	const rows: string[] = [];
	for (let i = index - 1; i >= from; i--) {
		const line = lines[i] ?? "";
		if (body(line).trim() === "") break;
		rows.unshift(line);
	}
	// A heading line or a card title immediately above the label means this label
	// opened a card rather than closed a band — there is nothing to measure.
	if (rows.length === 0) continue;
	bands.push({
		label: name,
		rows: rows.length,
		ink: rows.reduce((sum, row) => sum + body(row).split(FILL).length - 1, 0),
		// THE FLOOR IS THE BAND'S LAST ROW and it must be a full run of axisLine.
		// A row-COUNT check cannot see a missing floor, because the defective bands
		// had the right number of rows and simply lacked the glyph.
		floor: isFloor(rows[rows.length - 1] ?? "") ? 1 : 0,
		// Rows carrying no glyph at all: legal ABOVE a floor (the unplotted part of
		// a chart whose values round to no rows), never as the floor itself.
		blank: rows.filter(row => body(row).trim() === "").length,
	});
}

const shown = wanted.length > 0 ? bands.filter(band => wanted.includes(band.label)) : bands;

console.log(`label                rows  ink  floor  blank`);
for (const band of shown) {
	console.log(
		`${band.label.padEnd(20)} ${String(band.rows).padStart(4)} ${String(band.ink).padStart(4)} ${String(band.floor).padStart(6)} ${String(band.blank).padStart(6)}`,
	);
}
if (shown.length > 0) {
	const heights = shown.map(band => band.rows);
	console.log(`\nheights=${JSON.stringify(heights)} distinct=${new Set(heights).size}/${heights.length}`);
	console.log(`bands missing a floor: ${shown.filter(band => band.floor === 0).length}/${shown.length}`);
}